---
title: "Gross Synergy Driver"
author: "Ali Raisolsadat & Quan Dau"
date: "Latest Changes: 26 May 2024"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#' **************************************************************************************
#' **************************************************************************************

#' Function 1:
#' This function normalizes entire data-frame of indicator values for group of countries.
#' @param x is the data-frame to be normalized.
#' @return a normalized data-frame.
normalize_fun <- function(x) {
  norm_x <- as.matrix(x)
  return(data.frame(rescale(x, c(0,1))))
}

#' Function 2:
#' This function normalizes entire data-frame of indicator values between -100 - 100. 
#' @param x is the data-frame to be normalized.
#' @return a normalized data-frame.
normalize_pos_neg_perc_fun <- function(x) {
  norm_x <- as.matrix(x)
  return(data.frame(rescale(x, c(-100,100), na.rm = TRUE)))
}

#' Function 3:
#' This function cleans the indicator data. The processes is as follows:
#' Recursively: 
#' 1. Filter the countries by name and extract their data. 
#' 2. Add their data to a new data frame.
#' 3. Add the new data frame to a list 
#' @param sdg_ind_unclean_list is a list of unclean data
#' @return a list of cleaned data-frames with each column representing each country
#' and each row an observation of a specific indicator value for each country.
clean_indicator_data_fun <- function(sdg_ind_unclean_list) {
  #' find indicators that have more than one attribute.
  num_more_than_one_att <- c()
  for(i in 1:length(sdg_ind_unclean_list)) {
    if (ncol(sdg_ind_unclean_list[[i]]) > 4) {
      num_more_than_one_att <- rbind(num_more_than_one_att, i)
      print(i)
    }
  }
  if (length(num_more_than_one_att) != 0) {
    sdg_ind_unclean_list[[num_more_than_one_att]] <- NULL #remove them
  }
  
  #' The unclean data has four columns. 
  #' The fourth column is the data, associated to the country in the second column,
  #' for the observation date in first column. 
  #' Recursively: 
  #' 1. Filter the countries by name and extract their data. 
  #' 2. Add their data to a new data frame.
  #' 3. Add the new data frame to a list 
  sdg_indicator_selected_for_countries <- list()
  for (j in 1:length(sdg_ind_unclean_list)) {
    temp_ind_df <- data.frame()
    for (i in 1:length(COUNTRY_NAMES)) {
      temp_ind_data <- ((sdg_ind_unclean_list[[j]] %>% 
                           filter(Entity == COUNTRY_NAMES[i] & Year >= YEAR_THRESHOLD) %>%
                           complete(Year = YEAR_SEQUENCE))[,4] %>% data.frame())[,1]
      temp_ind_df <- rbind(temp_ind_df, temp_ind_data)
    }
    temp_ind_df <- (t(temp_ind_df))
    temp_ind_df <- normalize_fun(temp_ind_df)
    colnames(temp_ind_df) <- gsub(pattern = " ", replacement = "_", tolower(COUNTRY_NAMES))
    rownames(temp_ind_df) <- YEAR_SEQUENCE
    sdg_indicator_selected_for_countries[[j]] <- temp_ind_df
  }
  
  names(sdg_indicator_selected_for_countries) <- names(sdg_ind_unclean_list)
  print(names(sdg_indicator_selected_for_countries))
  return(sdg_indicator_selected_for_countries)
}

#' Function 4:
#' This function uses the cleaned data-frames to evaluate impact for a group of
#' countries provided by the user.
#' @param sdg_ind_clean_list is he list of cleaned data-frames
#' @return an impact matrix with each row representing the observation date, and
#' each column the impact of an indicator.
evaluate_dist_group_fun <- function(sdg_ind_clean_list) {
  cc <- data.frame()
  for (i in 1:length(sdg_ind_clean_list)) {
    dd <- sdg_ind_clean_list[[i]]
    one_dist_indicator <- sqrt(rowSums(diff(as.matrix(dd))^2, na.rm = TRUE))
    cc <- rbind(cc, one_dist_indicator)
  }
  cc <- data.frame(t(cc))
  colnames(cc) <- names(sdg_ind_clean_list)
  rownames(cc) <- as.Date(ISOdate(YEAR_SEQUENCE[-1], 1, 1))  # beginning of year
  cc$year <- YEAR_SEQUENCE[-1]
  #cc <- cc %>% filter(year <= 2020 & year >= 2000) #' This was the issue
  cc$year <- NULL
  return(cc)
}

#' Function 5:
#' This function uses the cleaned data-frames to evaluate impact for a single country
#' from the list of countries provided by the user.
#' @param sdg_ind_clean_list is he list of cleaned data-frames
#' @return an impact matrix with each row representing the observation date, and
#' each column the impact of an indicator.
evaluate_dist_individual_fun <- function(sdg_ind_clean_list) {
  country_list <- gsub(pattern = " ", replacement = "_", tolower(COUNTRY_NAMES))
  country_dist_mat_list <- list()
  for(j in 1:length(country_list)) {
    cc <- data.frame()
    for (i in 1:length(sdg_ind_clean_list)) {
      dd <- sdg_ind_clean_list[[i]][country_list[j]]
      one_dist_indicator <- sqrt(rowSums(diff(as.matrix(dd))^2, na.rm = TRUE))
      cc <- rbind(cc, one_dist_indicator)
    }
    cc <- data.frame(t(cc))
    colnames(cc) <- names(sdg_ind_clean_list)
    rownames(cc) <- as.Date(ISOdate(YEAR_SEQUENCE[-1], 1, 1))  # beginning of year
    cc$year <- YEAR_SEQUENCE[-1]
    #cc <- cc %>% filter(year <= 2020 & year >= 2000) #' This was the issue
    cc$year <- NULL
    country_dist_mat_list[[j]] <- cc
  }
  names(country_dist_mat_list) <- country_list
  return(country_dist_mat_list)
}

#' Function 6:
#' This function uses the cleaned data-frames to evaluate difference matrix for a group of
#' countries provided by the user.
#' @param sdg_ind_clean_list is he list of cleaned data-frames
#' @return an difference matrix with each row representing the observation date, and
#' each column the difference (historical change) of an indicator.
evaluate_grads_group_fun <- function(sdg_ind_clean_list) {
  cc <- data.frame()
  for (i in 1:length(sdg_ind_clean_list)) {
    dd <- sdg_ind_clean_list[[i]]
    one_grads_indicator <- rowMeans(diff(as.matrix(dd)), na.rm = TRUE)
    one_grads_indicator[one_grads_indicator < 0] <- -1
    one_grads_indicator[one_grads_indicator > 0] <- 1
    cc <- rbind(cc, one_grads_indicator)
  }
  cc <- data.frame(t(cc))
  colnames(cc) <- names(sdg_ind_clean_list)
  rownames(cc) <- as.Date(ISOdate(YEAR_SEQUENCE[-1], 1, 1))  # beginning of year
  cc$year <- YEAR_SEQUENCE[-1]
  #cc <- cc %>% filter(year <= 2020 & year >= 2000) #' This was the issue
  cc$year <- NULL
  return(cc)
}

#' Function 7:
#' This function uses the cleaned data-frames to evaluate difference matrix for a single 
#' country from the list of countries provided by the user.
#' @param sdg_ind_clean_list is he list of cleaned data-frames
#' @return an difference matrix with each row representing the observation date, and
#' each column the difference (historical change) of an indicator.
evaluate_grad_individual_fun <- function(sdg_ind_clean_list) {
  country_list <- gsub(pattern = " ", replacement = "_", tolower(COUNTRY_NAMES))
  country_grad_mat_list <- list()
  for(j in 1:length(country_list)) {
    cc <- data.frame()
    for (i in 1:length(sdg_ind_clean_list)) {
      dd <- sdg_ind_clean_list[[i]][country_list[j]]
      one_grads_indicator <- rowMeans(diff(as.matrix(dd)), na.rm = TRUE)
      one_grads_indicator[one_grads_indicator < 0] <- -1
      one_grads_indicator[one_grads_indicator > 0] <- 1
      cc <- rbind(cc, one_grads_indicator)
    }
    cc <- data.frame(t(cc))
    colnames(cc) <- names(sdg_ind_clean_list)
    rownames(cc) <- as.Date(ISOdate(YEAR_SEQUENCE[-1], 1, 1))  # beginning of year
    cc$year <- YEAR_SEQUENCE[-1]
    #cc <- cc %>% filter(year <= 2020 & year >= 2000)  #' This was the issue
    cc$year <- NULL
    country_grad_mat_list[[j]] <- cc
  }
  names(country_grad_mat_list) <- country_list
  return(country_grad_mat_list)
}

#' Function 8:
#' This function evaluates the distribution of positive contributions for each indicator by
#' the group of countries. 
#' @param contribution_list is a list of country contributions to indicators
#' @param indicator_names is a vector of indicator names
#' @return a data frame that has each country as column, each indicator name as row, and 
#' each observation is the distribution of a single country to the indicator through out the 
#' given years
cont_dist_fun <- function(contribution_list, indicator_names) {
  contribution_j_count <- data.frame()
  for (j in 1:length(COUNTRY_NAMES)) {
    contribution_j_data <- contribution_list[[j]]
    contribution_j_data <- contribution_j_data[indicator_names]
    Pos_Count <- rowSums(contribution_j_data[,1:ncol(contribution_j_data)] > 0, na.rm = TRUE)
    Neg_Count <- rowSums(contribution_j_data[,1:ncol(contribution_j_data)] < 0, na.rm = TRUE)
    contribution_j_count <- rbind(contribution_j_count, (Pos_Count / (Pos_Count + Neg_Count)))
  }
  contribution_j_count <- data.frame(t(contribution_j_count))
  colnames(contribution_j_count) <- COUNTRY_NAMES
  rownames(contribution_j_count) <- as.Date(ISOdate(NEW_YEAR_SEQ, 1, 1))  # beginning of year
  return(contribution_j_count)
}

#' Function 9:
#' This function evaluates the distribution of positive gross synergy
#' @param syn_df synergy 
#' @return positive contributions of gross synergy 
synergy_dist_fun <- function(syn_df) {
  
  Pos_Count <- colSums(syn_df[,1:ncol(syn_df)] > 0, na.rm = TRUE)
  Neg_Count <- colSums(syn_df[,1:ncol(syn_df)] < 0, na.rm = TRUE)
  syn_df_count <- Pos_Count / (Pos_Count + Neg_Count) * 100
  
  return(data.frame(t(syn_df_count)))
}

#' Function 10:
#' This function creates a contribution data-frame for each indicator. Each data-frame has 
#' countries as columns, years as rows, and each observation is the contribution to gross synergy 
#' of the indicator. The contributions are normalized in range -100% to 100%. 
#' @param contribution_list is a list of country contributions to indicators
#' @param indicator_names is a vector of indicator names
country_cont_fun <- function(contribution_list, ind_names) {
  indicator_contirbutions_by_country <- list()
  
  for (i in 1:length(ind_names)) {
    temp_df <- data.frame()
    for (j in 1:length(contribution_list)) {
      temp_df <- rbind(temp_df, contribution_list[[j]][,ind_names[i]])
    }
    temp_df <- data.frame(t(temp_df))
    colnames(temp_df) <- COUNTRY_NAMES
    rownames(temp_df) <- as.Date(ISOdate(NEW_YEAR_SEQ, 1, 1))  # beginning of year
    indicator_contirbutions_by_country[[i]] <- temp_df
  }
  
  norm_indicator_contirbutions_by_country <- list()
  for (i in 1:length(ind_names)) {
    dd <- indicator_contirbutions_by_country[[i]]
    new_dd <- data.frame()
    for (j in 1:nrow(dd)) {
      new_dd <- rbind(new_dd, as.matrix(dd[j,]))
    }
    norm_indicator_contirbutions_by_country[[i]] <- new_dd
  }
  
  names(norm_indicator_contirbutions_by_country) <- ind_names
  
  return(norm_indicator_contirbutions_by_country)
}

#' Function 11:
#' This function normalizes the synergy contribution rows that are larger than 100 and less than -100
#' to be in between -100 and 100. We use absolute value to consider both bounds.
#' @param cont_list is the synergy contribution list by each SDG
#' @param val_larger_than is the threshold for normalization
make_between_neg_pos_100 <- function(cont_list, val_larger_than) {
  for (i in 1:length(cont_list)) {
    x <- cont_list[[i]]
    ind <- sort(unique(row(x)[which(abs(x) > val_larger_than)]))
    
    if (!(is.integer(ind) && length(ind) == 0L)) {
      y = data.frame(t(apply(x[ind,], 1, function(x) x / max(abs(x))))) * 100 
      x[ind,] = y
    }
    
    cont_list[[i]] <- x
  }
  return(cont_list)
}

#' FUNCTION 12:
#' This function appends the synergy contributions for all SDG indicators into a 
#' large data frame.
#' @param cont_list is the synergy contribution list by each SDG
#' @return a large data frame with all the SDG synergy contributions for countries
create_all_cont <- function(cont_list) {
  x <- data.frame()
  for (i in 1:length(cont_list)) {
    x1 <- cont_list[[i]]
    new_df_names <- c("Indicator", "Year", colnames(x1))
    x1 <- cbind(rep(names(cont_list)[i], nrow(x1)), 
                format(as.Date(row.names(x1)), "%Y"),
                x1)
    colnames(x1) <- new_df_names
    row.names(x1) <- NULL
    
    
    x <- rbind.data.frame(x, x1)
  }
  return(x)
}

#' Function 13:
#' This function generates heat maps for the G7 countries' contributions to the gross synergy. 
#' @param normed_sdg_contributions_by_country is a list of normalized SDG contributions to G7 countries
#' @param loc is the location to save the heatmaps
heatmap_generator_g7 <- function(normed_sdg_contributions_by_country, loc) {
  
  for (i in 1:length(normed_sdg_contributions_by_country)) {
    sdg_df <- normed_sdg_contributions_by_country[[i]]
    colnames(sdg_df) <- gsub("\\.", " ", colnames(sdg_df))
    col_levels <- levels(colnames(sdg_df))
    
    sdg_df$Year <- as.Date(as.character(rownames(sdg_df)))
    sdg_df$Ind <- names(normed_sdg_contributions_by_country)[i]
    sdg_df$Ind <- gsub("ind", "SDG ", sdg_df$Ind)
    unique(sdg_df$Ind) 
    
    sdg_df_gather <- gather(sdg_df, key = "Country", value="Contribution",  -Year, -Ind)
    sdg_df_gather$Country <- factor(sdg_df_gather$Country, levels =  c("Canada", "France", "Germany", "Italy",  "Japan", "United Kingdom", "United States"))
    
    p1<- ggplot(sdg_df_gather, aes(Country, Year,  fill= Contribution))+
      geom_tile( stat = "identity", position = "identity", color = "white",
                 lwd = 1.5,
                 linetype = 1)+
      theme_few(base_size = 26)+
      labs(x = "", y = "Year") +
      scale_fill_gradientn(colors = hcl.colors(20, "Spectral"), na.value = "grey") +
      theme(plot.title = element_text(hjust = 0.5))+
      theme(legend.title = element_blank())+
      theme(axis.text.x =  element_text(angle = 45,vjust = 0.6))+
      geom_text(  aes(label = ifelse(is.na(Contribution), "", format(paste0(round(Contribution, 1), "%") ))) , size = 6, alpha = 0.7)+
      theme(legend.position = "none") 
    
    p2<- ggplot(sdg_df_gather, aes(Country,  Contribution))+
      geom_boxplot(aes(color = Country), lwd = 1.2)+
      theme_few(base_size = 26)+
      geom_jitter(aes(color= Country), alpha = 0.5 , size = 5,  position = position_jitter(width = 0.1))+
      theme(legend.position = "none")+
      ggtitle (unique(sdg_df$Ind)) +
      theme(plot.title = element_text(hjust = 0.5))+
      theme(axis.ticks.x = element_blank())+
      theme(axis.text.x = element_blank())+
      labs(x = "", y = "(%)") 
    
    
    joint_p <- p2 / p1 + plot_layout(widths = c(1, 1), heights = unit(c(1.7, 5), c('null', 'null')))
    filename_plot <- paste0(loc, "//", unique(sdg_df$Ind), ".jpeg")
    ggsave(filename_plot, plot = joint_p, height = 523.875, width = 285.75, units = "mm", dpi = 500)
    
  }
}
```


```{r}
#' Required libraries
library(tidyverse)
library(dplyr)
library(tidyr)
library(scales)
library(ggpubr)
library(grid)
library(gridExtra)
library(patchwork)
library(ggthemes)
library(janitor)

#' Constants. Please apply changes here. 
YEAR_THRESHOLD <- 1999
YEAR_SEQUENCE <- 1999:2020
NEW_YEAR_SEQ <- 2000:2020
SDG_INDICATORS_PATH <- "sdg_data"
COUNTRY_NAMES <- sort(c("Canada", "France", "Germany", "Italy", "Japan", "United Kingdom", "United States"))

#' Economic SDG indicator names
econ_ind_names <- tolower(c("ind1.1.1", "ind1.A.1(1)", "ind1.A.2(1)", "ind2.5.2", 
                            "ind3.1.1", "ind3.2.1", "ind3.2.2", "ind3.3.2", "ind3.4.1", "ind3.4.2", "ind3.6.1(1)", 
                            "ind3.B.1(1)", "ind6.1.1(1)", "ind6.2.1(1)", "ind7.1.1", "ind7.1.2", 
                            "ind7.2.1", "ind7.3.1", "ind8.1.1", "ind8.2.1", "ind8.4.2(1)", "ind8.4.2(2)","ind8.5.2(1)",
                            "ind9.1.2(1)", "ind9.1.2(2)", "ind9.1.2(3)", "ind9.2.1", "ind9.2.2(1)", "ind9.2.2(2)", 
                            "ind9.4.1", "ind9.5.1", "ind9.5.2", "ind9.C.1(1)", "ind9.C.1(2)")) 

#' Environmental SDG indicator names
envir_ind_names <- tolower(c("ind12.2.2(1)", "ind12.2.2(2)", "ind13.1.1(1)", "ind14.1.1(1)", 
                             "ind15.1.1", "ind15.1.2(1)", "ind15.4.1", "ind15.A.1(1)")) 

#' All of the indicator names
indicators_econ_envir_names <- c(econ_ind_names, envir_ind_names)

#' Read all the SDG indicator files into a list
filenames = list.files(path = SDG_INDICATORS_PATH, pattern="*.csv", full.names=TRUE)
sdg_indicator_selected_clean <- lapply(filenames, read.csv, row.names = 1)
indicatornames = gsub(pattern = ".csv", replacement = "", list.files(path = SDG_INDICATORS_PATH, pattern="*.csv"))
names(sdg_indicator_selected_clean) <- gsub("2ind","ind", indicatornames)

for(i in 1:length(sdg_indicator_selected_clean)) {
  dd <- sdg_indicator_selected_clean[[i]]
  dd <- dd %>% clean_names()
  dd <- as.data.frame(normalize_fun(as.matrix(dd)))
  sdg_indicator_selected_clean[[i]] <- dd
}
```


```{r figure 1(a)}
#' Compute the impact for the group of countries.
indicator_impact_group <- evaluate_dist_group_fun(sdg_indicator_selected_clean)

#' Compute the impact for individual countries in the group.
indicator_impact_countries_list <- evaluate_dist_individual_fun(sdg_indicator_selected_clean)

#' Construct average impact for G7 countries - Economic indicators
econ_impact_ind_df <- data.frame()
for (i in 1:length(indicator_impact_countries_list)) {
  econ_impact <- rowMeans(indicator_impact_countries_list[[i]][econ_ind_names], na.rm = TRUE)
  econ_impact_ind_df <- rbind(econ_impact_ind_df, econ_impact)
}
econ_impact_ind_df <- rbind(econ_impact_ind_df, rowMeans(indicator_impact_group[econ_ind_names], na.rm = TRUE))
econ_impact_ind_df <- data.frame(t(econ_impact_ind_df))
colnames(econ_impact_ind_df) <- c(COUNTRY_NAMES, "G7")
rownames(econ_impact_ind_df) <- NEW_YEAR_SEQ
write.csv(x = econ_impact_ind_df, file = paste0("results/plot_1_a_distance_average_economic_indicators.csv")) #figure 1(a)
```


```{r figure 1(b)}
#' Construct average impact for G7 countries - Environment indicators
env_impact_ind_df <- data.frame()
for (i in 1:length(indicator_impact_countries_list)) {
  env_impact_ind_data <- rowMeans(indicator_impact_countries_list[[i]][envir_ind_names], na.rm = TRUE)
  env_impact_ind_df <- rbind(env_impact_ind_df, env_impact_ind_data)
}
env_impact_ind_df <- rbind(env_impact_ind_df, rowMeans(indicator_impact_group[envir_ind_names], na.rm = TRUE))
env_impact_ind_df <- data.frame(t(env_impact_ind_df))
colnames(env_impact_ind_df) <- c(COUNTRY_NAMES, "G7")
rownames(env_impact_ind_df) <- NEW_YEAR_SEQ
write.csv(x = env_impact_ind_df, file = paste0("results/plot_1_b_distance_average_environment_indicators.csv")) #figure 1(b)
```

```{r figure 2}
#' Write the impact results.
save(x = indicator_impact_countries_list, file = "results/plot_2_domestic_changes.RData") # figure 2
```



```{r}
#' Compute the difference for the group of countries.
indicator_gradient_group <- evaluate_grads_group_fun(sdg_indicator_selected_clean)

#' Compute the difference for individual countries in the group.
indicator_gradient_countries_list <- evaluate_grad_individual_fun(sdg_indicator_selected_clean)

#' This section reads the goal direction of the SDG indicators.
true_direction_df <- read.csv("partial_true_direction_un.csv")
true_direction_df <- true_direction_df %>% filter(included == 1)
true_direction_df_copy <- true_direction_df %>% filter(tolower(indicator) %in% indicators_econ_envir_names)
true_direction_df_copy <- true_direction_df_copy[order(true_direction_df_copy$indicator),]

#' Create a data-frame that has rows either +1 or -1 to show the increasing and decreasing of 
#' SDG indicators. 
target_indicator_df <- data.frame()
for(i in 1:nrow(true_direction_df_copy)) {
  target_indicator_df <- rbind(target_indicator_df, rep(true_direction_df_copy$direction[i], length(YEAR_SEQUENCE[-1])))
}
target_indicator_df <- data.frame(t(target_indicator_df))
colnames(target_indicator_df) <- colnames(indicator_gradient_group)
rownames(target_indicator_df) <- as.Date(ISOdate(YEAR_SEQUENCE[-1], 1, 1))  # beginning of year
target_indicator_df$year <- as.Date(ISOdate(YEAR_SEQUENCE[-1], 1, 1))  # beginning of year
target_indicator_df <- target_indicator_df %>% filter(year <= "2020-01-01" & year >= "2000-01-01")
target_indicator_df$year <- NULL

synergy_direction_df <- indicator_gradient_group * target_indicator_df
synergy_direction_df[is.na(synergy_direction_df)] <- NA
```


```{r}
#' Compute synergy and synergy total based on the definition. 
#' Start by creating an empty data-frame.
sum_indicator_impact_countries <- data.frame(matrix(0, ncol = ncol(indicator_impact_group), nrow = nrow(indicator_impact_group)))

#' Loop through the country impact list and add them to each other
for (i in 1:(length(COUNTRY_NAMES))) {
  sum_indicator_impact_countries <- sum_indicator_impact_countries + indicator_impact_countries_list[[i]]
}

#' Apply the synergy formula
synergy <- sum_indicator_impact_countries - indicator_impact_group
colnames(synergy) <- names(sdg_indicator_selected_clean)
rownames(synergy) <- as.Date(ISOdate(NEW_YEAR_SEQ, 1, 1))  # beginning of year
```


```{r, figure 3}
#' Compute synergy total using the definition: synergy x Ic
gross_synergy <- (synergy * synergy_direction_df) / length(COUNTRY_NAMES) 
econ_gross_syn <- gross_synergy[econ_ind_names]
colnames(econ_gross_syn) <- toupper(str_replace_all(colnames(econ_gross_syn), "ind", "SDG "))

envr_gross_syn <- gross_synergy[envir_ind_names]
colnames(envr_gross_syn) <- toupper(str_replace_all(colnames(envr_gross_syn), "ind", "SDG "))
gross_synergy_new_names <- cbind(econ_gross_syn, envr_gross_syn) #' figure 3(a)

#' Add Year column
envr_gross_syn_cpy <- cbind("Year" = format(as.Date(row.names(envr_gross_syn)), format = "%Y"), gross_synergy_new_names)
write.csv(x = envr_gross_syn_cpy, file = "results/plot_3_a_gross_synergy_g7.csv", row.names = FALSE)


positive_gorss_syn_dist <- synergy_dist_fun(gross_synergy_new_names) # figure 3(b)
positive_gorss_syn_dist <- cbind.data.frame("Positive Gross Synergy", positive_gorss_syn_dist)
colnames(positive_gorss_syn_dist) <- c("Indicator", colnames(positive_gorss_syn_dist)[-1])
write.csv(x = positive_gorss_syn_dist, file = "results/plot_3_b_dist_of_positive_gross_synergy_g7.csv", row.names = FALSE)
```

```{r, figure 4, warning=FALSE}
#' Compute Contribution of each country to the overall synergy. 
country_synergy_contribution_list <- list()
for (i in 1:length(COUNTRY_NAMES)) {
  contribution_j <- (indicator_impact_countries_list[[i]] - (indicator_impact_group/length(COUNTRY_NAMES))) / gross_synergy * 100
  contribution_j[contribution_j == -Inf] <- 100
  contribution_j[contribution_j == Inf] <- 100
  contribution_j <- contribution_j / length(COUNTRY_NAMES)
  
  country_synergy_contribution_list[[i]] <- contribution_j
}
names(country_synergy_contribution_list) <- names(indicator_impact_countries_list)


#' CHANGES HERE - June 6 - 2023:

#' Figure 4 code
economic_indicator_contirbutions_by_country <- country_cont_fun(country_synergy_contribution_list, econ_ind_names)
#' NORMALIZED HERE
economic_indicator_contirbutions_by_country_copy <- 
  make_between_neg_pos_100(economic_indicator_contirbutions_by_country, 100)
save(x = economic_indicator_contirbutions_by_country_copy, file = "results/plot_4_economic_indicator_contributions.RData")

#'Normalized contributions to environmental indicators' gross synergy by G7 countries. 
environment_indicator_contirbutions_by_country <- country_cont_fun(country_synergy_contribution_list, envir_ind_names)
#' NORMALIZED HERE
environment_indicator_contirbutions_by_country_copy <- 
  make_between_neg_pos_100(environment_indicator_contirbutions_by_country, 100)
save(x = environment_indicator_contirbutions_by_country_copy, file = "results/plot_4_environment_indicator_contributions.RData")

#' PLEASE SEE FUNCTION 12
#' MAKE THE LARGE SDG EXCEL FILE HERE:
synergy_cont_econ_df <- create_all_cont(economic_indicator_contirbutions_by_country_copy)
synergy_cont_econ_df$Indicator <- toupper(str_replace_all(synergy_cont_econ_df$Indicator, "ind", "SDG "))
synergy_cont_env_df <- create_all_cont(environment_indicator_contirbutions_by_country_copy)
synergy_cont_env_df$Indicator <- toupper(str_replace_all(synergy_cont_env_df$Indicator, "ind", "SDG "))

write.csv(x = rbind.data.frame(synergy_cont_econ_df, synergy_cont_env_df), 
          row.names = FALSE,
          file = paste0("results/synergy_contribution.csv"))
```


```{r, plot 5}
#' CHANGES HERE - June 4 - 2023

#' Evaluate the average for all years, for each economic indicator, given a country
all_years_average_for_econ_indicators_df <- 
  data.frame(lapply(economic_indicator_contirbutions_by_country_copy, 
                    function(x) apply(x,2,median, na.rm = TRUE )))
all_years_average_for_econ_indicators_df <- data.frame(t(all_years_average_for_econ_indicators_df))
all_years_average_for_econ_indicators_df <- 
  cbind.data.frame("Indicator" = toupper(str_replace_all(row.names(all_years_average_for_econ_indicators_df), "ind", "SDG ")),
                                                        all_years_average_for_econ_indicators_df)
row.names(all_years_average_for_econ_indicators_df) <- NULL
write.csv(x = all_years_average_for_econ_indicators_df, 
          file = paste0("results/plot5_years_median_for_econ_indicators.csv"), row.names = FALSE)
apply(all_years_average_for_econ_indicators_df[,2:8], 2, median, na.rm = TRUE)
 
#' Evaluate the average for all years, for each environmental indicator, given a country
all_years_average_for_env_indicators_df <- 
  data.frame(lapply(environment_indicator_contirbutions_by_country_copy, 
                    function(x) apply(x,2,median, na.rm = TRUE )))
all_years_average_for_env_indicators_df <- data.frame(t(all_years_average_for_env_indicators_df))
all_years_average_for_env_indicators_df <- 
  cbind.data.frame("Indicator" = toupper(str_replace_all(row.names(all_years_average_for_env_indicators_df), "ind", "SDG ")),
                                                        all_years_average_for_env_indicators_df)
row.names(all_years_average_for_env_indicators_df) <- NULL
write.csv(x = all_years_average_for_env_indicators_df, 
          file = paste0("results/plot5_years_median_for_env_indicators.csv"), row.names = FALSE)
apply(all_years_average_for_env_indicators_df[,2:8], 2, median, na.rm = TRUE)


#' Make the large average data frame here
#' Join the average tables and give them SDG ID
years_average_for_all_indicators_df <- rbind(all_years_average_for_econ_indicators_df, all_years_average_for_env_indicators_df)
write.csv(x = years_average_for_all_indicators_df, 
          row.names = FALSE,
          file = paste0("results/median_year_synergy_contribution.csv"))
```